### ISSUE TITLE
Corrigir bug do carrinho de compras

### ISSUE THREAD

**Issue by moisesmk** [AfonsoJoao/Quick#3]
O carrinho de compras está com um bug que ao clicar em adicionar produto ao carrinho é exibida a seguinte mensagem: Erro ao adicionar produto

**Comment by AfonsoJoao** [comment]
Bug resolvido modificando a rota para a library CarrinhoCompra do projeto, pois o ambiente online do hostgator é case sensitive e havia algumas letras em minusculo no link que deveriam ser maiúsculas
