### ISSUE TITLE
Erro no email

### ISSUE THREAD

**Issue by moisesmk** [AfonsoJoao/Quick#6]
O sistema permite que dois clientes possam se cadastrar com o mesmo email.

**Comment by AfonsoJoao** [comment]
O problema foi resolvido adicionando uma função de verificação no momento do cadastro do novo cliente. Essa função consulta o banco de dados e verifica se o e-mail informado já está sendo utilizado, caso o e-mail já esteja em uso a mensagem "O e-mail inserido não está disponível" aparece na tela e o usuário não poderá usar esse e-mail.
